import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { canManageInventory } from "@/lib/permissions";

/**
 * Tent kit definitions using the REAL DB item naming format:
 * "SubCategory - ItemName - Description"
 * as generated by import-master-data.ts → buildItemName()
 */
const TENT_KIT_DEFINITIONS = [
    {
        name: "Full Frame Tent",
        subcategoryPattern: "14*28 FF",
        componentPatterns: [
            { nameContains: "14*28 FF - Inner", type: "INNER", qtyPerKit: 1 },
            { nameContains: "14*28 FF - non woven carpet", type: "CARPET", qtyPerKit: 4 },
            { nameContains: "14*28 FF - connector pipes", type: "PIPES", qtyPerKit: 6 },
            { nameContains: "14*28 FF - outer", type: "OUTER", qtyPerKit: 1 },
            { nameContains: "14*28 FF - Sockets", type: "SOCKETS", qtyPerKit: 1 },
        ],
    },
    {
        name: "Half Frame Tent",
        subcategoryPattern: "14*28 HF",
        componentPatterns: [
            { nameContains: "14*28 HF - Inner", type: "INNER", qtyPerKit: 1 },
            { nameContains: "14*28 HF - non woven carpet", type: "CARPET", qtyPerKit: 4 },
            { nameContains: "14*28 HF - connector pipes", type: "PIPES", qtyPerKit: 6 },
            { nameContains: "14*28 HF - outer", type: "OUTER", qtyPerKit: 1 },
            { nameContains: "14*28 HF - Sockets", type: "SOCKETS", qtyPerKit: 1 },
        ],
    },
    {
        name: "18*22 Tent",
        subcategoryPattern: "18*22",
        componentPatterns: [
            { nameContains: "18*22  - inner", type: "INNER", qtyPerKit: 1 },
            { nameContains: "18*22  - outer", type: "OUTER", qtyPerKit: 1 },
            { nameContains: "18*22  - non woven carpet", type: "CARPET", qtyPerKit: 4 },
            { nameContains: "18*22  - connector pipes", type: "PIPES", qtyPerKit: 1 },
            { nameContains: "18*22  - Sockets", type: "SOCKETS", qtyPerKit: 1 },
        ],
    },
    {
        name: "24*24 Tent",
        subcategoryPattern: "24*24",
        componentPatterns: [
            { nameContains: "24*24 - inner", type: "INNER", qtyPerKit: 1 },
            { nameContains: "24*24 - outer", type: "OUTER", qtyPerKit: 1 },
            { nameContains: "24*24 - non woven carpet (12ft*24ft)", type: "CARPET_LARGE", qtyPerKit: 1 },
            { nameContains: "24*24 - non woven carpet (6ft)", type: "CARPET_SMALL", qtyPerKit: 2 },
            { nameContains: "24*24 - connector pipes", type: "PIPES", qtyPerKit: 1 },
            { nameContains: "24*24 - Sockets", type: "SOCKETS", qtyPerKit: 1 },
        ],
    },
    {
        name: "Canopy Tent",
        subcategoryPattern: "Canopy",
        componentPatterns: [
            { nameContains: "Canopy - Cloth", type: "CLOTH", qtyPerKit: 1 },
            { nameContains: "Canopy - Pillars", type: "PILLARS", qtyPerKit: 1 },
            { nameContains: "Canopy - Hinges", type: "HINGES", qtyPerKit: 1 },
        ],
    },
    {
        name: "Dining Tent 15*30ft",
        subcategoryPattern: "Dining Tent 15*30 ft",
        componentPatterns: [
            { nameContains: "Dining Tent 15*30 ft - Cloth", type: "CLOTH", qtyPerKit: 1 },
            { nameContains: "Dining Tent 15*30 ft - Pillars", type: "PILLARS", qtyPerKit: 1 },
            { nameContains: "Dining Tent 15*30 ft - Hinges", type: "HINGES", qtyPerKit: 1 },
        ],
    },
    {
        name: "Dining Tent 30*60ft",
        subcategoryPattern: "Dining Tent 30*60 ft",
        componentPatterns: [
            { nameContains: "Dining Tent 30*60 ft - Cloth", type: "CLOTH", qtyPerKit: 1 },
            { nameContains: "Dining Tent 30*60 ft - Pillars", type: "PILLARS", qtyPerKit: 1 },
            { nameContains: "Dining Tent 30*60 ft - Hinges", type: "HINGES", qtyPerKit: 1 },
        ],
    },
];

/**
 * POST /api/tent-kits/setup-migration
 * Creates BundleTemplate records for all tent kit types from existing DB items.
 * Safe to run multiple times – skips already-existing kits.
 * Uses the actual DB item naming format: "SubCategory - ItemName - Description"
 */
export async function POST() {
    try {
        const session = await getServerSession(authOptions);
        if (!session || !canManageInventory(session.user.role)) {
            return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
        }

        // Get Tents category
        const tentsCategory = await prisma.category.findFirst({
            where: { name: { contains: "Tent", mode: "insensitive" } },
        });

        if (!tentsCategory) {
            return NextResponse.json({ error: "Tents category not found in database" }, { status: 404 });
        }

        const results: {
            kitName: string;
            status: "created" | "skipped" | "partial";
            componentsFound: number;
            componentsMissing: string[];
        }[] = [];

        for (const kitDef of TENT_KIT_DEFINITIONS) {
            // Skip if already exists
            const existing = await prisma.bundleTemplate.findUnique({ where: { name: kitDef.name } });
            if (existing) {
                results.push({
                    kitName: kitDef.name,
                    status: "skipped",
                    componentsFound: 0,
                    componentsMissing: [],
                });
                continue;
            }

            // Find the subcategory
            const subcategory = await prisma.subcategory.findFirst({
                where: {
                    categoryId: tentsCategory.id,
                    name: { contains: kitDef.subcategoryPattern, mode: "insensitive" },
                },
            });

            // Find component items by their actual DB name patterns
            const componentIds: { itemId: string; quantityPerBaseUnit: number }[] = [];
            const missing: string[] = [];

            for (const comp of kitDef.componentPatterns) {
                // First search within the Tents category (more precise)
                const item = await prisma.item.findFirst({
                    where: {
                        name: { contains: comp.nameContains, mode: "insensitive" },
                        categoryId: tentsCategory.id,
                    },
                });

                if (item) {
                    componentIds.push({ itemId: item.id, quantityPerBaseUnit: comp.qtyPerKit });
                    // Mark as kit component with its type
                    await prisma.item.update({
                        where: { id: item.id },
                        data: {
                            isKitComponent: true,
                            componentType: comp.type,
                            quantityPerKit: comp.qtyPerKit,
                        },
                    });
                } else {
                    missing.push(comp.nameContains);
                }
            }

            // Create virtual base item for the kit
            const baseItem = await prisma.item.create({
                data: {
                    categoryId: tentsCategory.id,
                    subcategoryId: subcategory?.id || null,
                    name: kitDef.name,
                    description: `Complete ${kitDef.name} kit`,
                    quantityAvailable: 0,
                    condition: "GOOD",
                    isKitComponent: false,
                },
            });

            // Create BundleTemplate
            if (componentIds.length > 0) {
                await prisma.bundleTemplate.create({
                    data: {
                        name: kitDef.name,
                        description: `${kitDef.name} - Complete Kit`,
                        baseItemId: baseItem.id,
                        items: {
                            createMany: { data: componentIds },
                        },
                    },
                });
            }

            results.push({
                kitName: kitDef.name,
                status: missing.length > 0 ? "partial" : "created",
                componentsFound: componentIds.length,
                componentsMissing: missing,
            });
        }

        const created = results.filter((r) => r.status === "created").length;
        const skipped = results.filter((r) => r.status === "skipped").length;
        const partial = results.filter((r) => r.status === "partial").length;

        return NextResponse.json({
            success: true,
            summary: { created, skipped, partial },
            details: results,
        });
    } catch (error) {
        console.error("Error running tent kit migration:", error);
        return NextResponse.json({ error: "Migration failed", details: String(error) }, { status: 500 });
    }
}
